### PR TITLE
Backend service created | Google Oauth Implemented | Users'  google profile data storage implemented

### PR DESCRIPTION
**Pull request by rks-031**
**Issue Title:** Create backend service to for better persistence of state
**Issue Number:** #11 

<br/>

_**The following depicts the functionality added to the project:**_
1. Creation of signup page.
2. Enabling login and signup routes.
3. Updating user model.
4. Creating Google auth client.
5. Initializing MongoDB database.
6. Implementing passport configuration.
7. Modifying user model.
8. Integrating Google OAuth to the server.
9. Adding Google authentication functionality.
10. Implementing sign-in functionality.
11. Enabling storage of user details upon sign-in.

<br/>

_**Here's a demo of the above said:**_
https://github.com/beckn/use-case-gen-frontend/assets/103258259/788c73fd-8fd8-4c3c-a72f-02601c97ef59

### CODE REVIEW

**Comment by jayesh9747** [comment]
@rks-031  pls check again the task provided in the issue , we maintain the session not only update the data on our data base . please go through again

**Comment by rks-031** [comment]
> @rks-031 pls check again the task provided in the issue , we maintain the session not only update the data on our data base . please go through again

**Comment by rks-031** [comment]
> @rks-031 pls check again the task provided in the issue , we maintain the session not only update the data on our data base . please go through again

@jayesh9747 could you please explain maintaining the session? As per my knowledge, the entire codespace is as it is and only additional functionality of google auth via backend(as mentioned in the task) has been implemented.
Kindly reply at your earliest convenience so that I'll be able to work upon the same.

**Comment by jayesh9747** [comment]
@rks-031 , maintain the session using cookies provided by the Google API to display user details on the application screen. If you have any queries, feel free to ask on the Discord channel FIDE.

**Pull request closed without merging**
